# Generated by Django 3.2 on 2021-05-02 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress_api', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=10)),
                ('symbol', models.CharField(blank=True, default='$', max_length=10)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'CURRENCY',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('large', models.FloatField(blank=True, default=0)),
                ('height', models.FloatField(blank=True, default=0)),
                ('width', models.FloatField(blank=True, default=0)),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PROVIDER',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TOWN',
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'VEHICLE_BRAND',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'VEHICLE_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('patent', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='', max_length=20)),
                ('motor', models.CharField(default='', max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands', to='serviexpress_api.vehiclebrand')),
                ('type_v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='serviexpress_api.vehicletype')),
            ],
            options={
                'db_table': 'VEHICLE',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='serviexpress_api.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='serviexpress_api.product')),
            ],
            options={
                'db_table': 'PRODUCT_PRICE',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, db_table='PRODUCT_PROVIDER', related_name='providers', to='serviexpress_api.Provider'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_date', models.DateField(auto_now_add=True)),
                ('birth_day', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comuna', to='serviexpress_api.town')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLIENT',
            },
        ),
    ]
