# Generated by Django 3.1.3 on 2020-11-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id_u', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('rut_dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('tarjeta_credito', models.IntegerField(max_length=15)),
                ('contrasena', models.CharField(max_length=20)),
                ('tipousuario', models.IntegerField(max_length=1)),
            ],
        ),
    ]
