# Generated by Django 3.1.3 on 2020-11-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0002_auto_20201109_0302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
