# Generated by Django 3.1.3 on 2020-11-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobikeApp', '0003_auto_20201109_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
