FROM python:3.8.5

# Installing Oracle instant client
WORKDIR    /opt/oracle
RUN        apt-get update && apt-get install -y libaio1 wget unzip \
            && wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
            && unzip instantclient-basiclite-linuxx64.zip \
            && rm -f instantclient-basiclite-linuxx64.zip \
            && cd /opt/oracle/instantclient* \
            && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci \
            && echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
            && ldconfig

WORKDIR    /app
# Copy my project folder content into /app container directory
COPY       . .
RUN        pip3 install pipenv
RUN        pipenv install
RUN        pipenv run python manage.py collectstatic --noinput --clear
EXPOSE     8000

ENTRYPOINT ["pipenv", "run", "server"]
